INSERT INTO Right_User (key, wording) VALUES
('GroupCreate','Création d''un groupe'),
('GroupUpdate','Modification d''un groupe'),
('GroupeDelete','Suppresion d''un groupe'),
('GroupRead','Lecture de groupe'),
('PromotionCreate','Création d''une promotion'),
('PromotionUpdate','Modification d''une promotion'),
('PromotionDelete','Suppresion d''une promotion'),
('PromotionRead','Lecture de promotion'),
('StudentCreate','Création d''un étudiant'),
('StudentUpdate','Modification d''un étudiant'),
('StudentDelete','Suppresion d''un étudiant'),
('StudentRead','Lecture d''étudiant'),
('AccountCreate','Création d''un compte utilisateur'),
('AccountUpdate','Modification d''un compte utilisateur'),
('AccountDelete','Suppresion d''un compte utilisateur'),
('AccountRead','Lecture de compte utilisateur'),
('RoleCreate','Création d''un rôle utilisateur'),
('RoleUpdate','Modification d''un rôle utilisateur'),
('RoleDelete','Suppresion d''un rôle utilisateur'),
('RoleRead','Lecture de rôle utilisateur'),
('RightRead','Lecture de droit utilisateur'),
('TimesheetCreate','Création d''une feuille de présence'),
('TimesheetUpdate','Modification d''une feuille de présence'),
('TimesheetDelete','Suppresion d''une feuille de présence'),
('TimesheetRead','Lecture de feuille de présence'),
('Recognition', 'Utilisation de la reconnaissance faciale');